const translations = {
  th: {
    skip: 'ข้ามไปยังรายการ', tagline: 'ค้นหาเครื่องที่ใช่ เพื่อโอกาสครั้งใหม่', language: 'ภาษา',
    eyebrow: 'ภาพรวมตลาดโทรศัพท์', heading: 'ค้นหาโทรศัพท์', intro: 'เครื่องมือสอง เครื่องเสีย และอะไหล่จากทั่วประเทศไทย', refresh: 'รีเฟรชข้อมูล',
    total: 'รายการทั้งหมด', totalHint: 'รายการในชุดข้อมูล', newTotal: 'รายการใหม่', newHint: 'รายการที่เพิ่งค้นพบ', sourcesTotal: 'เว็บไซต์ที่ค้นหา', sourcesHint: 'แหล่งข้อมูล', updated: 'เวลาที่อัปเดตล่าสุด', updatedHint: 'เวลาประเทศไทย (UTC+7)',
    demoTitle: 'ข้อมูลตัวอย่าง', demoText: 'รายการ ราคา และผู้ขายเป็นข้อมูลสมมติ ลิงก์ประกาศใช้เพื่อสาธิตเท่านั้น', filters: 'ตัวกรอง', clearAll: 'ล้างทั้งหมด', search: 'ค้นหา', searchPlaceholder: 'รุ่น หรืออาการเสีย…', brand: 'ยี่ห้อ', model: 'รุ่น', price: 'ราคา (บาท)', minPrice: 'ราคาต่ำสุด', maxPrice: 'ราคาสูงสุด', min: 'ต่ำสุด', max: 'สูงสุด', condition: 'สภาพเครื่อง', source: 'เว็บไซต์ต้นทาง', location: 'จังหวัด / พื้นที่', newOnly: 'เฉพาะรายการใหม่', newBadge: 'ใหม่',
    results: 'รายการโทรศัพท์', loading: 'กำลังโหลดข้อมูล…', sort: 'เรียงตาม', newest: 'ใหม่ล่าสุด', priceAsc: 'ราคาต่ำสุด', priceDesc: 'ราคาสูงสุด', emptyTitle: 'ไม่พบรายการที่ตรงกัน', emptyText: 'ลองเปลี่ยนคำค้นหรือขยายช่วงราคา', clearFilters: 'ล้างตัวกรอง', footnote: 'เวลาแสดงตามเขตเวลาประเทศไทย · ราคาที่แสดงเป็นราคาประกาศ', footer: 'ข้อมูล · กันยายน 2026', detailHeading: 'รายละเอียดโทรศัพท์', closeDetail: 'ปิดรายละเอียด', noScript: 'โปรดเปิดใช้งาน JavaScript เพื่อดูรายการและใช้ตัวกรอง',
    allBrands: 'ทุกยี่ห้อ', allModels: 'ทุกรุ่น', allConditions: 'ทุกสภาพ', allSources: 'ทุกเว็บไซต์', allLocations: 'ทุกพื้นที่', other: 'อื่น ๆ', unknownPrice: 'ไม่ทราบราคา', placeholderImage: 'ภาพตัวอย่าง', placeholderAlt: 'ภาพตัวอย่างสำหรับ {model} ไม่ใช่ภาพสินค้าจริง', noImage: 'ไม่มีภาพประกาศ', noLink: 'ไม่มีลิงก์ประกาศ', original: 'ดูประกาศต้นฉบับ', originalLabel: 'ดูประกาศต้นฉบับ {title}{demo} — เปิดแท็บใหม่', demoLink: ' (ลิงก์สาธิต)', foundAt: 'พบเมื่อ: {date}', imageDisclaimer: 'ภาพตัวอย่าง ไม่ใช่ภาพสินค้าจริง', seller: 'ผู้ขาย', area: 'พื้นที่', dataSource: 'แหล่งข้อมูล', listingAge: 'อายุประกาศ', firstFound: 'พบครั้งแรก', lastChecked: 'ตรวจสอบล่าสุด', listingId: 'รหัสรายการ', defect: 'อาการเสีย', status: 'สถานะ', originalUrl: 'URL ต้นฉบับ', unspecified: 'ไม่ระบุ', active: 'ยังประกาศขาย', sold: 'ขายแล้ว', removed: 'นำประกาศออกแล้ว', notes: 'หมายเหตุ: {notes}{demo}', noNotes: 'ไม่มีหมายเหตุ', fictional: ' รายการนี้เป็นข้อมูลสมมติ ไม่สามารถซื้อได้จริง', rangeError: 'ราคาต่ำสุดต้องไม่เกินราคาสูงสุด', resultSummary: 'แสดง {shown} จาก {total} รายการ{demo}', demoSuffix: ' · ข้อมูลตัวอย่าง', loadedDemo: 'โหลดข้อมูลตัวอย่างเรียบร้อยแล้ว', loaded: 'โหลดข้อมูลเรียบร้อยแล้ว', refreshFailed: 'รีเฟรชไม่สำเร็จ กำลังแสดงข้อมูลเดิม กรุณาลองอีกครั้ง', loadFailed: 'โหลดข้อมูลไม่สำเร็จ กรุณาตรวจสอบการเชื่อมต่อแล้วกดรีเฟรชข้อมูล', noData: 'ยังไม่มีข้อมูล', minutesAgo: '{count} นาทีที่แล้ว', hoursAgo: '{count} ชั่วโมงที่แล้ว', daysAgo: '{count} วันที่แล้ว'
  },
  en: {
    skip: 'Skip to listings', tagline: 'Find the right device for a fresh opportunity', language: 'Language',
    eyebrow: 'Phone market overview', heading: 'Find phones', intro: 'Used phones, broken devices and parts from across Thailand', refresh: 'Refresh data',
    total: 'Total listings', totalHint: 'Listings in the dataset', newTotal: 'New listings', newHint: 'Recently discovered listings', sourcesTotal: 'Sites searched', sourcesHint: 'Data sources', updated: 'Last updated', updatedHint: 'Thailand time (UTC+7)',
    demoTitle: 'Demo data', demoText: 'Listings, prices and sellers are fictional. Listing links are for demonstration only.', filters: 'Filters', clearAll: 'Clear all', search: 'Search', searchPlaceholder: 'Model or defect…', brand: 'Brand', model: 'Model', price: 'Price (baht)', minPrice: 'Minimum price', maxPrice: 'Maximum price', min: 'Min', max: 'Max', condition: 'Condition', source: 'Source website', location: 'Province / area', newOnly: 'New listings only', newBadge: 'New',
    results: 'Phone listings', loading: 'Loading data…', sort: 'Sort by', newest: 'Newest', priceAsc: 'Lowest price', priceDesc: 'Highest price', emptyTitle: 'No matching listings', emptyText: 'Try another search or widen the price range', clearFilters: 'Clear filters', footnote: 'Times use the Thailand time zone · Prices shown are asking prices', footer: 'Data · September 2026', detailHeading: 'Phone details', closeDetail: 'Close details', noScript: 'Enable JavaScript to view listings and use filters.',
    allBrands: 'All brands', allModels: 'All models', allConditions: 'All conditions', allSources: 'All websites', allLocations: 'All areas', other: 'Other', unknownPrice: 'Price unknown', placeholderImage: 'Sample image', placeholderAlt: 'Sample image for {model}, not the actual item', noImage: 'No listing image', noLink: 'No listing link', original: 'View original listing', originalLabel: 'View original listing for {title}{demo} — opens in a new tab', demoLink: ' (demo link)', foundAt: 'Found: {date}', imageDisclaimer: 'Sample image, not the actual item', seller: 'Seller', area: 'Area', dataSource: 'Source', listingAge: 'Listing age', firstFound: 'First discovered', lastChecked: 'Last checked', listingId: 'Listing ID', defect: 'Defect', status: 'Status', originalUrl: 'Original URL', unspecified: 'Not specified', active: 'Active', sold: 'Sold', removed: 'Removed', notes: 'Notes: {notes}{demo}', noNotes: 'No notes', fictional: ' This listing is fictional and cannot be purchased.', rangeError: 'Minimum price must not exceed maximum price', resultSummary: 'Showing {shown} of {total} listings{demo}', demoSuffix: ' · Demo data', loadedDemo: 'Demo data loaded', loaded: 'Data loaded', refreshFailed: 'Refresh failed. Showing the previous data; please try again.', loadFailed: 'Could not load data. Check your connection and refresh.', noData: 'No data available', minutesAgo: '{count} minutes ago', hoursAgo: '{count} hours ago', daysAgo: '{count} days ago'
  },
  de: {
    skip: 'Zu den Angeboten springen', tagline: 'Das passende Gerät für eine neue Chance finden', language: 'Sprache',
    eyebrow: 'Überblick über den Handymarkt', heading: 'Handys finden', intro: 'Gebrauchte und defekte Handys sowie Ersatzteile aus ganz Thailand', refresh: 'Daten aktualisieren',
    total: 'Angebote gesamt', totalHint: 'Angebote im Datensatz', newTotal: 'Neue Angebote', newHint: 'Kürzlich entdeckte Angebote', sourcesTotal: 'Durchsuchte Websites', sourcesHint: 'Datenquellen', updated: 'Zuletzt aktualisiert', updatedHint: 'Thailand-Zeit (UTC+7)',
    demoTitle: 'Beispieldaten', demoText: 'Angebote, Preise und Verkäufer sind frei erfunden. Die Links dienen nur zur Demonstration.', filters: 'Filter', clearAll: 'Alle löschen', search: 'Suche', searchPlaceholder: 'Modell oder Defekt…', brand: 'Marke', model: 'Modell', price: 'Preis (Baht)', minPrice: 'Mindestpreis', maxPrice: 'Höchstpreis', min: 'Min.', max: 'Max.', condition: 'Zustand', source: 'Quellwebsite', location: 'Provinz / Gebiet', newOnly: 'Nur neue Angebote', newBadge: 'Neu',
    results: 'Handyangebote', loading: 'Daten werden geladen…', sort: 'Sortieren nach', newest: 'Neueste', priceAsc: 'Niedrigster Preis', priceDesc: 'Höchster Preis', emptyTitle: 'Keine passenden Angebote', emptyText: 'Ändere die Suche oder erweitere die Preisspanne', clearFilters: 'Filter löschen', footnote: 'Zeitangaben in thailändischer Zeitzone · Angezeigte Preise sind Angebotspreise', footer: 'Daten · September 2026', detailHeading: 'Handydetails', closeDetail: 'Details schließen', noScript: 'Aktiviere JavaScript, um Angebote und Filter zu verwenden.',
    allBrands: 'Alle Marken', allModels: 'Alle Modelle', allConditions: 'Alle Zustände', allSources: 'Alle Websites', allLocations: 'Alle Gebiete', other: 'Andere', unknownPrice: 'Preis unbekannt', placeholderImage: 'Beispielbild', placeholderAlt: 'Beispielbild für {model}, nicht der tatsächliche Artikel', noImage: 'Kein Angebotsbild', noLink: 'Kein Angebotslink', original: 'Originalangebot ansehen', originalLabel: 'Originalangebot für {title}{demo} ansehen — öffnet einen neuen Tab', demoLink: ' (Demo-Link)', foundAt: 'Gefunden: {date}', imageDisclaimer: 'Beispielbild, nicht der tatsächliche Artikel', seller: 'Verkäufer', area: 'Gebiet', dataSource: 'Quelle', listingAge: 'Alter des Angebots', firstFound: 'Zuerst gefunden', lastChecked: 'Zuletzt geprüft', listingId: 'Angebots-ID', defect: 'Defekt', status: 'Status', originalUrl: 'Original-URL', unspecified: 'Nicht angegeben', active: 'Aktiv', sold: 'Verkauft', removed: 'Entfernt', notes: 'Hinweise: {notes}{demo}', noNotes: 'Keine Hinweise', fictional: ' Dieses Angebot ist frei erfunden und kann nicht gekauft werden.', rangeError: 'Der Mindestpreis darf den Höchstpreis nicht überschreiten', resultSummary: '{shown} von {total} Angeboten{demo}', demoSuffix: ' · Beispieldaten', loadedDemo: 'Beispieldaten geladen', loaded: 'Daten geladen', refreshFailed: 'Aktualisierung fehlgeschlagen. Die bisherigen Daten werden weiterhin angezeigt.', loadFailed: 'Daten konnten nicht geladen werden. Prüfe die Verbindung und aktualisiere erneut.', noData: 'Keine Daten verfügbar', minutesAgo: 'vor {count} Minuten', hoursAgo: 'vor {count} Stunden', daysAgo: 'vor {count} Tagen'
  }
};

export const languages = ['th', 'en', 'de'];
export function initialLanguage() {
  let saved = null;
  try { saved = localStorage.getItem('phone-finder-language'); } catch {}
  if (languages.includes(saved)) return saved;
  const browserLanguage = (navigator.language || 'th').toLowerCase().split('-')[0];
  return languages.includes(browserLanguage) ? browserLanguage : 'th';
}
export function translate(language, key, values = {}) {
  const dictionary = translations[language] || translations.th;
  return Object.entries(values).reduce((text, [name, value]) => text.split(`{${name}}`).join(value), dictionary[key] ?? key);
}
